apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: todo-app
        image: naukite/unir:todo
        ports:
        - containerPort: 3000